routes/web.php
<?php
Route::get('/', 'ProductsController@home');
Auth::routes();

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('login.admin');
Route::get('/login/writer', 'Auth\LoginController@showWriterLoginForm')->name('login.writer');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm')->name('register.admin');
Route::get('/register/writer', 'Auth\RegisterController@showWriterRegisterForm')->name('register.writer');

Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/login/writer', 'Auth\LoginController@writerLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin')->name('register.admin');
Route::post('/register/writer', 'Auth\RegisterController@createWriter')->name('register.writer');

Route::view('/home', 'home')->middleware('auth');

Route::group(['middleware' => 'auth:admin'], function () {
    Route::view('/admin', 'admin');
    Route::resource('products','ProductController');
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
    Route::get('/writers/{writer}/editpassword', 'WriterController@editpassword')->name('writers.editpassword');
    Route::put('/writers/{writer}/updatepassword', 'WriterController@updatepassword')->name('writers.updatepassword');
    Route::resource('writers', 'WriterController');



});

Route::group(['middleware' => 'auth:writer'], function () {
    Route::view('/writer', 'writer');
    Route::resource('products','ProductController');
    Route::resource('category','CategoryController');
    Route::resource('orders','OrderController');


});


Route::group(['middleware' => 'auth'], function () {
    Route::view('/home', 'home');
    Route::view('/checkout','checkout');
    Route::view('/payment','payment');
    Route::view('/success','success');


    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

    //Route::resource('/maincategory','MainCategoryController');
    Route::resource('categorys','CategorysController');

    Route::get('cart', 'ProductsController@cart');




    Route::get('add-to-cart/{id}', 'ProductsController@addToCart');

    Route::patch('update-cart', 'ProductsController@update');

    Route::delete('remove-from-cart', 'ProductsController@remove');

    Route::get('/order', 'ProductsController@order')->name('orders');
    Route::post('/checkout/order', 'ProductsController@placeOrder')->name('place.order');
    Route::get('/orderdetails', 'ProductsController@vieworder')->name('view.order');

  //  Route::get('/showorder/{id}', 'ProductsController@showorder')->name('show.order');

    Route::get('/product', 'ProductsController@index');
    Route::patch('payment', 'ProductsController@updateorder')->name('payment');

    Route::resource('product','ProductsController');
    //Route::resource('order','OrderController');
    Route::get('/showorder/{id}', 'OrderController@show')->name('show.order');




});




Route::view('/logout','logout');
Route::view('/checkout','checkout');



Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

resources/views/category.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show category</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ url('product') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Category:</strong>
                {{ $category->name }}
            </div>
        </div>
        @foreach ( $category->products as $product)
        @if ($product->unit > 0)
        <div class="col-xs-18 col-sm-6 col-md-3">
            <div class="thumbnail">
              <td width="1%"><img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" /></td>
                <div class="caption">
                <h4><a href="{{route('product.show',$product->id) }}">{{ $product->name }}</a></h4>
                    <p><strong>Price: </strong> RM {{ $product->price }}</p>
                    <p><strong>Unit Left: </strong> {{ $product->unit }}</p>

                    <p><strong>Category: </strong> {{ $product->category -> name }}</p>
                    <p class="btn-holder"><a href="{{ url('add-to-cart/'.$product->id) }}" class="btn btn-warning btn-block text-center" role="button">Add to cart</a> </p>
                </div>
            </div>
        </div>
        @endif
        @endforeach


    </div>
@endsection

resources/views/checkout.blade.php
@extends('layout')

@section('title', 'Check Out')

@section('content')
<div class="checkout-panel">

  <div class="panel-body">
    <h2 class="title">Checkout here!</h2>

    <div class="progress-bar">
      <div class="step active"></div>
      <div class="step active"></div>
      <div class="step"></div>
      <div class="step"></div>
    </div>

    <div class="payment-method">
      <label for="card" class="method card">
        <div class="card-logos">
          <img src="https://designmodo.com/demo/checkout-panel/img/visa_logo.png"/>
          <img src="https://designmodo.com/demo/checkout-panel/img/mastercard_logo.png"/>
        </div>

        <div class="radio-input">
          <input id="card" type="radio" name="payment">
          Pay RM {{$order->grand_total}} with credit card
        </div>
      </label>

      <label for="paypal" class="method paypal">
        <img src="https://designmodo.com/demo/checkout-panel/img/paypal_logo.png"/>
        <div class="radio-input">
          <input id="paypal" type="radio" name="payment">
          Pay  RM {{$order->grand_total}} with PayPal
        </div>
      </label>
    </div>

    <div class="input-fields">
      <div class="column-1">
        <label for="cardholder">Name</label>
        <input type="text" id="cardholder" placeholder="e.g. Richard Bovell" />

        <div class="column-2">
          <label for="cardnumber">Card Number</label>
          <input type="password" id="cardnumber"/>

          <span class="info">* CVV or CVC is the card security code, unique three digits number on the back of your card separate from its number.</span>
        </div>
        <div class="small-inputs">
          <div>
            <label for="date">Expiry</label>
            <select id="expiry-date">
                <option>MM</option>
                <option value="1">01</option>
                <option value="2">02</option>
                <option value="3">03</option>
                <option value="4">04</option>
                <option value="5">05</option>
                <option value="6">06</option>
                <option value="7">07</option>
                <option value="8">08</option>
                <option value="9">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
            <span>/</span>
             <select id="expiry-date">
                <option>YYYY</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
                <option value="2023">2023</option>
                <option value="2024">2024</option>
                <option value="2025">2025</option>
                <option value="2026">2026</option>
                <option value="2027">2027</option>
                <option value="2028">2028</option>
                <option value="2029">2029</option>
                <option value="2030">2030</option>
                <option value="2031">2031</option>
            </select>
          </div>

          <div>
            <label for="verification">CVV / CVC *</label>
            <input type="password" maxlength="4" placeholder="123"/>
            <span class="info">* CVV or CVC is the card security code, unique three digits number on the back of your card separate from its number.</span>
          </div>
        </div>

      </div>

    </div>
  </div>
  <input name="payment_status" type="hidden" value="1">

  <div class="panel-footer">
    <a href="{{ url('/product') }}"><button class="btn back-btn">Back</button></a>
    <a href="{{ route('payment') }}"><button type="submit" class="btn next-btn"  >Confirm And Pay</button></a>
  </div>
</div>

@endsection
  @section('scripts')
  <script type="text/javascript">

  $(document).ready(function() {

  $('.method').on('click', function() {
    $('.method').removeClass('blue-border');
    $(this).addClass('blue-border');
  });

})
var $cardInput = $('.input-fields input');

$('.next-btn').on('click', function(e) {

  $cardInput.removeClass('warning');

  $cardInput.each(function() {
     var $this = $(this);
     if (!$this.val()) {
       $this.addClass('warning');
     }
  })
});
</script>
@endsection

resources/views/create.blade.php
@extends('layout')

@section('title', 'Product Create')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ url('products') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{action('ProductsController@store') }}" method="POST">
    @csrf

     <div class="row">
       <div class="col-xs-12 col-sm-12 col-md-12">
           <div class="form-group">
               <strong>Image:</strong>
               <input type="file" name="image" accept="image/gif, image/jpeg, image/png">

           </div>
       </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                <input type="number" name="price" class="form-control" placeholder="price">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Unit:</strong>
                <input type="number" name="unit" class="form-control" placeholder="unit">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/details.blade.php
@extends('layout')

@section('title', 'Product Details')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ url('products') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
<img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" />
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $product->description }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                {{ $product->price }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Unit left:</strong>
                {{ $product->unit }}
            </div>
        </div>
    </div>

@endsection

resources/views/edit.blade.php
@extends('layout')

@section('title', 'Product Edit')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ url('products') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

  <form action="{{action('ProductsController@updateproduct')}}" method="PUT">
        @csrf
        @method('PUT')

         <div class="row">
           <div class="col-xs-12 col-sm-12 col-md-12">
               <div class="form-group">
                   <strong>Image:</strong>
                   <input type="file" name="image" accept="image/gif, image/jpeg, image/png">

               </div>
           </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="description">{{ $product->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price:</strong>
                    <input type="text" name="price" value="{{ $product->price }}" class="form-control" placeholder="price">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Unit:</strong>
                    <input type="text" name="unit" value="{{ $product->unit }}" class="form-control" placeholder="unit">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/home.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                     Hi there, regular user
                </div>
                <a href="{{ url('/product') }}" class="btn btn-warning"><i class="fa fa-angle-right"></i> Continue Shopping</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/logout.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Utar E-Fllea Market</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>
                        <a href="{{ route('register') }}">Register</a>
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Utar E-Flea Martket
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Documentation</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/main.blade.php
@extends('welcome')

@section('title', 'Utar E-Flea Market')

@section('content')
<head>
  <style>
  .container-products {
    margin-top:100px;
    margin-left: 200px;
    margin-right: 30px;
    align-items: center;
  }

  .item{
    margin-bottom: 8px;
  }
  .thumbnail {
      padding: 0px;

      height: auto;
      width: auto;


  }

  .thumbnail img {
      width: 50%;
  }

  .thumbnail .caption{
      margin: 7px;
  }
  .sidenav {
    width: 130px;
    height: auto;
    position: fixed;
    z-index: 1;
    top: 60px;
    left: 10px;
    background: #eee;
    overflow-x: hidden;
    padding: 8px 0;
  }

  .sidenav a {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 15px;
    color: #2196F3;
    display: block;
  }

  .sidenav a:hover {
    color: #064579;
  }
 .side{
   margin-top: 100px;
 }

    </style>
    <head>
       <div class= "side">
        <div class="sidenav">
          	<strong>Category</strong>
            @foreach($categories->sortBy('name')  as $category)
            <a href="{{ route('category.show',$category->id) }}">{{ $category->name }}</a>

            @endforeach
        <a href="#about">About</a>
        <a href="#services">Services</a>
        <a href="#contact">Contact</a>
      </div>
      </div>
    <div class="container-products">

        <div class="row">

            @foreach($products->sortByDesc('updated_at') as $product)
            @if ($product->unit > 0)


                <div class="col-xs-18 col-sm-6 col-md-3 item ">
                    <div class="thumbnail">

                        <img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" />


                        <div class="caption">
                        <h4>{{ $product->name }}</h4>
                            <p><strong>Price: </strong> RM {{ $product->price }}</p>
                            <p><strong>Unit Left: </strong> {{ $product->unit }}</p>
                            <p><strong>Category: </strong> {{ $product->category -> name }}</p>
                            <p class="btn-holder"><a href="{{ url('add-to-cart/'.$product->id) }}" class="btn btn-warning btn-block text-center" role="button">Add to cart</a> </p>
                        </div>
                    </div>
                </div>
                @endif
            @endforeach

        </div><!-- End row -->

    </div>

@endsection

resources/views/order.blade.php
@extends('layout')

@section('title', 'Order')

@section('content')

<section class="section-pagetop bg-dark">
    <div class="container clearfix">
        <h2 class="title-page">Checkout</h2>
    </div>
</section>
<table id="cart" class="table table-hover table-condensed">
    <thead>
    <tr>
        <th style="width:50%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:8%">Quantity</th>
        <th style="width:22%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
    </tr>
    </thead>
    <tbody>


    <?php $total = 0 ?>

@foreach($orders as $order)

            <?php $total += $order['price'] * $order['quantity'] ?>



            <tr>
                <td data-th="Product">
                    <div class="row">

                        <div class="col-sm-3 hidden-xs"><img src="data:image/jpeg;base64,{{$order['image']}}" width="100" height="100" class="img-responsive"/></div>
                        <div class="col-sm-9">
                            <h4 class="nomargin" nema="name">{{ $order['name'] }}</h4>
                        </div>
                    </div>
                </td>
                <td data-th="Price">${{ $order['price'] }}</td>
                <td data-th="Quantity">
                  <td data-th="Price" name="quantity">{{ $order['quantity'] }}</td>

                </td>
                <td data-th="Subtotal" class="text-center">${{ $order['price'] * $order['quantity'] }}</td>

            </tr>
        @endforeach



    </tbody>

</table>

    <section class="section-content bg padding-y">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    @if (Session::has('error'))
                        <p class="alert alert-danger">{{ Session::get('error') }}</p>
                    @endif
                </div>
            </div>
<a href="{{ url('/cart') }}" class="btn btn-primary"><i class="fa fa-angle-left"></i> Back</a>
            <form action="{{ route('place.order') }}" method="POST" role="form">
                @csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <header class="card-header">
                                <h4 class="card-title mt-2">Billing Details</h4>
                            </header>
                            <article class="card-body">
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label>First name</label>
                                        <input type="text" class="form-control" name="first_name">
                                    </div>
                                    <div class="col form-group">
                                        <label>Last name</label>
                                        <input type="text" class="form-control" name="last_name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Address</label>
                                    <input type="text" class="form-control" name="address">
                                </div>

                                    <div class="form-group  col-md-6">
                                        <label>Phone Number</label>
                                        <input type="text" class="form-control" name="phone_number">
                                    </div>
                                </div>


                            </article>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <header class="card-header">
                                        <h4 class="card-title mt-2">Your Order</h4>
                                    </header>
                                    <article class="card-body">
                                        <dl class="dlist-align">
                                            <dt>Total cost: </dt>
                                            <dd class="text-right h5 b" name="grand_total"> {{ $total }} </dd>
                                        </dl>
                                    </article>
                                </div>
                            </div>
                            <div class="col-md-12 mt-4">

                                <button type="submit" class="subscribe btn btn-success btn-lg btn-block">Place Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/products.blade.php
<?php
use App\Common;
?>
@extends('layout')

@section('title', 'Products')

@section('content')
<head>
<style>
.sidenav {
  width: 130px;
  position: fixed;
  z-index: 1;
  top: 20px;
  left: 10px;
  background: #eee;
  overflow-x: hidden;
  padding: 8px 0;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 15px;
  color: #2196F3;
  display: block;
}

.sidenav a:hover {
  color: #064579;
}


</style>

</head>


  <div class="sidenav">
    	<strong>Category</strong>
      @foreach($categories->sortBy('name') as $category)
      <a href="{{ route('categorys.show',$category->id) }}">{{ $category->name }}</a>

      @endforeach
  <a href="#about">About</a>
  <a href="#services">Services</a>
  <a href="#contact">Contact</a>
</div>

    <div class="container products">

        <div class="row">

            @foreach($products->sortByDesc('updated_at') as $product)
            @if ($product->unit > 0)
                <div class="col-xs-18 col-sm-6 col-md-3">
                    <div class="thumbnail">
                      <td width="1%"><img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" /></td>
                        <div class="caption">
                        <h4><a href="{{route('product.show',$product->id) }}">{{ $product->name }}</a></h4>
                            <p><strong>Price: </strong> RM {{ $product->price }}</p>
                            <p><strong>Unit Left: </strong> {{ $product->unit }}</p>

                            <p><strong>Category: </strong> {{ $product->category -> name }}</p>
                            <p class="btn-holder"><a href="{{ url('add-to-cart/'.$product->id) }}" class="btn btn-warning btn-block text-center" role="button">Add to cart</a> </p>
                        </div>
                    </div>
                </div>
                  @endif
            @endforeach



        </div><!-- End row -->

    </div>

@endsection
@section('scripts')
<script type="text/javascript">

</script>
@endsection

resources/views/showorder.blade.php
@extends('layout')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Order</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('view.order') }}"> Back</a>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Item:</strong>
            {{ $order->items}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Status:</strong>
            @foreach ( $order->items as $item) <li><a href={{ route('product.show',$item->product_id) }}>{{$item->product->name}} x {{$item->quantity}}</a></li> @endforeach
        </div>
    </div>

</div>
@endsection

resources/views/success.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                     Payment success! Thank You For shoppong With Us.
                </div>
                <a href="{{ url('/product') }}" class="btn btn-warning"><i class="fa fa-angle-right"></i> Continue Shopping</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/writer.blade.php
@extends('layouts.auth')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    Hi there, awesome seller
                </div>
                <a href="{{ url('/products') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue To Product Page</a>
                <a href="{{ url('/category') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue To Category Page</a>
                <a href="{{ url('/orders') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue To Order Page</a>

            </div>
        </div>
    </div>
</div>

@endsection