routes/web.php
<?php
Route::get('/', 'ProductsController@home');
Auth::routes();

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('login.admin');
Route::get('/login/writer', 'Auth\LoginController@showWriterLoginForm')->name('login.writer');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm')->name('register.admin');
Route::get('/register/writer', 'Auth\RegisterController@showWriterRegisterForm')->name('register.writer');

Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/login/writer', 'Auth\LoginController@writerLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin')->name('register.admin');
Route::post('/register/writer', 'Auth\RegisterController@createWriter')->name('register.writer');

Route::view('/home', 'home')->middleware('auth');

Route::group(['middleware' => 'auth:admin'], function () {
    Route::view('/admin', 'admin');
    Route::resource('products','ProductController');
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
    Route::get('/writers/{writer}/editpassword', 'WriterController@editpassword')->name('writers.editpassword');
    Route::put('/writers/{writer}/updatepassword', 'WriterController@updatepassword')->name('writers.updatepassword');
    Route::resource('writers', 'WriterController');



});

Route::group(['middleware' => 'auth:writer'], function () {
    Route::view('/writer', 'writer');
    Route::resource('products','ProductController');
    Route::resource('category','CategoryController');
    Route::resource('orders','OrderController');


});


Route::group(['middleware' => 'auth'], function () {
    Route::view('/home', 'home');
    Route::view('/checkout','checkout');
    Route::view('/payment','payment');
    Route::view('/success','success');


    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

    //Route::resource('/maincategory','MainCategoryController');
    Route::resource('categorys','CategorysController');

    Route::get('cart', 'ProductsController@cart');




    Route::get('add-to-cart/{id}', 'ProductsController@addToCart');

    Route::patch('update-cart', 'ProductsController@update');

    Route::delete('remove-from-cart', 'ProductsController@remove');

    Route::get('/order', 'ProductsController@order')->name('orders');
    Route::post('/checkout/order', 'ProductsController@placeOrder')->name('place.order');
    Route::get('/orderdetails', 'ProductsController@vieworder')->name('view.order');

  //  Route::get('/showorder/{id}', 'ProductsController@showorder')->name('show.order');

    Route::get('/product', 'ProductsController@index');
    Route::patch('payment', 'ProductsController@updateorder')->name('payment');

    Route::resource('product','ProductsController');
    //Route::resource('order','OrderController');
    Route::get('/showorder/{id}', 'OrderController@show')->name('show.order');




});




Route::view('/logout','logout');
Route::view('/checkout','checkout');



Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  protected $fillable = [
      'name',  'product_id',
  ];

  public function products()
  {
    return $this->hasMany(Product::class);
  }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $categories = Category::all();

      return view('categorys.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categorys.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
          'name' => 'required|max:100',

      ]);


            $category = new Category();
            $category->name = $request->name;

            $category->save();
      return redirect()->route('category.index')
                      ->with('success','Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categorys.show',compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categorys.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
      $request->validate([
          'name'=>'required',

      ]);

      $category->name =  $request->name;

      $category->save();

      return redirect('/category')->with('success', 'Category updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {

      $category->delete();

      return redirect()->route('category.index')
                      ->with('success','Category deleted successfully');
    }
}

app/Http/Controllers/CategorysController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use Illuminate\Http\Request;

class CategorysController extends Controller
{
  /**
   * Display the specified resource.
   *
   * @param  \App\Category  $category
   * @return \Illuminate\Http\Response
   */
  public function show(Category $category)
  {
      return view('category',compact('category'));
  }
}

resources/views/categorys/create.blade.php
@extends('layouts.auth')

@section('content')
<head>
	<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

<style>
.btn.btn-back {
	margin-top: 20px;
	margin-bottom: 15px;
	margin-left: 20px;
}

.btn-add {
	margin-left: 13px;
	margin-bottom: 40px;
	height: auto;
}
hr {
			margin-bottom: 20px;
	}
</style>
</head>

<div class="container">
	<div class="row">
		<a class="btn btn-back btn-primary" href="{{ route('category.index') }}"> Back</a>
	</div>

	<div class="row">
		<h3 class="header-text"> Add New category </h3>
	</div>



	@if ($errors->any())
	<div class="alert alert-danger">
			<strong>Whoops!</strong> There were some problems with your input.<br><br>
			<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
			</ul>
	</div>
	@endif

	<form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data">
	@csrf
	<hr>


		<div class="row">
			<div class="form-group col-md-12">
				<strong>Name:</strong>
				<input type="text" name="name" class="form-control" placeholder="Name" required focus>
				<span class="text-danger">{{ $errors->first('name') }}</span>
			</div>
			<button type="submit" class="btn btn-success ">Add</button>

		</div>
	</form>
</div>

@endsection

resources/views/categorys/edit.blade.php
@extends('layouts.auth')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<style>
    .btn.btn-back {
        margin-top: 20px;
        margin-bottom: 15px;
        margin-left: 20px;
    }

    .header-text {
        margin-top: 10px;
        margin-left: 20px;
        margin-bottom: 5px;
        font-size: 30px;
        font-family: 'Raleway', sans-serif;
        font-weight: bold;
    }

    .btn-update {
        margin-left: 1px;
        margin-bottom: 40px;
    }

    hr {
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('category.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Edit category </h3>
    </div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('category.update',$category->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="form-group col-md-12">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $category->name }}" class="form-control" placeholder="Name">
				<span class="text-danger">{{ $errors->first('name') }}</span>
            </div>



        </div>

        <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
</div>
</form>
</div>
@endsection

resources/views/categorys/index.blade.php
@extends('layouts.auth')

@section('content')
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Utar E-Flea Market Inventory Management System</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('category.create') }}"> + Create New category</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th width="280px">Action</th>
        </tr>

        @foreach ($categories->sortBy('name') as $category)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td><a href={{ route('category.show',$category->id) }}>{{ $category->name }}</a></td>
            <td>


                    <a class="btn btn-primary" href="{{ route('category.edit',$category->id) }}">Edit</a>


            </td>

        </tr>

        @endforeach

    </table>


@endsection

resources/views/categorys/show.blade.php
@extends('layouts.auth')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show category</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ url('category') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Category:</strong>
                {{ $category->name }}
            </div>
        </div>
        @foreach ( $category->products as $product)

        <div class="col-xs-18 col-sm-6 col-md-3">
            <div class="thumbnail">
              <td width="1%"><img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" /></td>
                <div class="caption">
                <h4><a href="{{route('product.show',$product->id) }}">{{ $product->name }}</a></h4>
                    <p><strong>Price: </strong> RM {{ $product->price }}</p>
                    <p><strong>Unit Left: </strong> {{ $product->unit }}</p>

                    <p><strong>Category: </strong> {{ $product->category -> name }}</p>
                </div>
            </div>
        </div>

        @endforeach

    </div>
@endsection