routes/web.php
<?php
Route::get('/', 'ProductsController@home');
Auth::routes();

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('login.admin');
Route::get('/login/writer', 'Auth\LoginController@showWriterLoginForm')->name('login.writer');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm')->name('register.admin');
Route::get('/register/writer', 'Auth\RegisterController@showWriterRegisterForm')->name('register.writer');

Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/login/writer', 'Auth\LoginController@writerLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin')->name('register.admin');
Route::post('/register/writer', 'Auth\RegisterController@createWriter')->name('register.writer');

Route::view('/home', 'home')->middleware('auth');

Route::group(['middleware' => 'auth:admin'], function () {
    Route::view('/admin', 'admin');
    Route::resource('products','ProductController');
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
    Route::get('/writers/{writer}/editpassword', 'WriterController@editpassword')->name('writers.editpassword');
    Route::put('/writers/{writer}/updatepassword', 'WriterController@updatepassword')->name('writers.updatepassword');
    Route::resource('writers', 'WriterController');



});

Route::group(['middleware' => 'auth:writer'], function () {
    Route::view('/writer', 'writer');
    Route::resource('products','ProductController');
    Route::resource('category','CategoryController');
    Route::resource('orders','OrderController');


});


Route::group(['middleware' => 'auth'], function () {
    Route::view('/home', 'home');
    Route::view('/checkout','checkout');
    Route::view('/payment','payment');
    Route::view('/success','success');


    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

    //Route::resource('/maincategory','MainCategoryController');
    Route::resource('categorys','CategorysController');

    Route::get('cart', 'ProductsController@cart');




    Route::get('add-to-cart/{id}', 'ProductsController@addToCart');

    Route::patch('update-cart', 'ProductsController@update');

    Route::delete('remove-from-cart', 'ProductsController@remove');

    Route::get('/order', 'ProductsController@order')->name('orders');
    Route::post('/checkout/order', 'ProductsController@placeOrder')->name('place.order');
    Route::get('/orderdetails', 'ProductsController@vieworder')->name('view.order');

  //  Route::get('/showorder/{id}', 'ProductsController@showorder')->name('show.order');

    Route::get('/product', 'ProductsController@index');
    Route::patch('payment', 'ProductsController@updateorder')->name('payment');

    Route::resource('product','ProductsController');
    //Route::resource('order','OrderController');
    Route::get('/showorder/{id}', 'OrderController@show')->name('show.order');




});




Route::view('/logout','logout');
Route::view('/checkout','checkout');



Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

app/Writer.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Writer extends Authenticatable
{
    use Notifiable;

    /**
     * @var string
     */
    protected $guard = 'writer';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function products()
    {
    return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/WriterController.php
<?php

namespace App\Http\Controllers;

use App\Writer;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;


class WriterController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */


  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {

    $writers = Writer::latest()->paginate(5);

    return view('writers.index', compact('writers'))
      ->with('i', (request()->input('page', 1) - 1) * 5);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('writers.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $request->validate([
      'name' => 'required|string|max:255',
      'email' => 'required|string|email|max:255|unique:writers',
      'password' => 'required|string|min:8|confirmed',
    ]);

    $writer = new Writer();
    $writer->name = $request->name;
    $writer->email = $request->email;
    $writer->password = Hash::make($request->password);
    $writer->save();

    return redirect()->route('writers.index')
      ->with('success', 'writer created successfully.');
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\writer  $writer
   * @return \Illuminate\Http\Response
   */
  public function show(Writer $writer)
  {
    return view('writers.show', compact('writer'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\writer  $writer
   * @return \Illuminate\Http\Response
   */
  public function edit(Writer $writer)
  {
    return view('writers.edit', compact('writer'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Writer  $writer
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Writer $writer)
  {
    $request->validate([
      'name' => 'required|string|max:255',
      'email' => 'required|string|email|max:255',
    ]);
    $writer->name = $request->name;
    $writer->email = $request->email;

    $writer->update();
    return redirect()->route('writers.index')
      ->with('success', 'writer updated successfully');
  }

  public function editpassword(Writer $writer)
  {
    return view('writers.editpassword', compact('writer'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\writer  $writer
   * @return \Illuminate\Http\Response
   */
  public function updatepassword(Request $request, Writer $writer)
  {
    $request->validate([
      'password' => 'required|string|min:8|confirmed',
    ]);
    $writer->password = Hash::make($request->password);

    $writer->update();
    return redirect()->route('writers.index')
      ->with('success', 'writer Password updated successfully');
  }
  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\writer $writer
   * @return \Illuminate\Http\Response
   */
   public function destroy(Writer $writer)
     {

       $writer->delete();

       return redirect()->route('writers.index')
         ->with('success', 'writer deleted successfully');
     }

}

resources/views/writers/create.blade.php
@extends('layouts.auth')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .btn-add {
            margin-top: 10px;
            margin-left: 13px;
            margin-bottom: 40px;
        }

        hr {
            margin-bottom: 20px;
        }
    </style>
</head>
<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('writers.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Add New Seller </h3>
    </div>


    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('writers.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-md-12">
                        <strong>Name:</strong>
                        <input type="text" name="name" class="form-control" placeholder="Name" required focus>
        				<span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
        <div class="form-group col-md-12">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" placeholder="Email" required focus>
				<span class="text-danger">{{ $errors->first('email') }}</span>
            </div>
            <div class="form-group col-md-12">
                  <strong>Password:</strong>
                  <input id="password" type="password" class="form-control" name="password" required autocomplete="new-password" placeholder="Password" required focus>
                  <!-- <input type="password" name="password1" class="form-control" placeholder="Password"> -->

              </div>
              <div class="form-group col-md-12">
                <strong>Confirm Password:</strong>
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password" placeholder="Confirm Password" required focus>
                <!-- <input type="password" name="password2" class="form-control" placeholder="Confirm Password"> -->
				<span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
            </div>

            <button type="submit" class="btn btn-add btn-success col-sm-2">Add</button>
        </div>
    </form>
</div>

@endsection

resources/views/writers/edit.blade.php
@extends('layouts.auth')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<style>
    .btn.btn-back {
        margin-top: 20px;
        margin-bottom: 15px;
        margin-left: 20px;
    }

    .header-text {
        margin-top: 10px;
        margin-left: 20px;
        margin-bottom: 5px;
        font-size: 30px;
        font-family: 'Raleway', sans-serif;
        font-weight: bold;
    }

    .btn-update {
        margin-left: 1px;
        margin-bottom: 40px;
    }

    hr {
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('writers.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Edit Seller </h3>
    </div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('writers.update',$writer->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="form-group col-md-12">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $writer->name }}" class="form-control" placeholder="Name">
				<span class="text-danger">{{ $errors->first('name') }}</span>
            </div>


            <div class="form-group col-md-12">
                <strong>Email:</strong>
                <input type="email" name="email" value="{{ $writer->email }}" class="form-control" placeholder="Email">
				<span class="text-danger">{{ $errors->first('email') }}</span>
            </div>

        </div>

        <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
</div>
</form>
</div>
@endsection

resources/views/writers/editpassword.blade.php
@extends('layouts.auth')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<style>
    .btn.btn-back {
        margin-top: 20px;
        margin-bottom: 15px;
        margin-left: 20px;
    }

    .header-text {
        margin-top: 10px;
        margin-left: 20px;
        margin-bottom: 5px;
        font-size: 30px;
        font-family: 'Raleway', sans-serif;
        font-weight: bold;
    }

    .btn-update {
        margin-left: 1px;
        margin-bottom: 40px;
    }

    hr {
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('writers.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Change Password </h3>
    </div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif




    <form action="{{ route('writers.updatepassword',$writer->id) }}" method="POST">

        @csrf
        @method('PUT')


    <form action="{{ route('writers.updatepassword',$writer->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="form-group col-md-12">
                <strong>New Password:</strong>
                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">
				<span class="text-danger">{{ $errors->first('password') }}</span>
                <!-- <input type="password" name="password" value="{{ $writer->password }}" class="form-control" placeholder="Password"> -->
            </div>


            <div class="form-group col-md-12">
                <strong>Confirm Password:</strong>
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
				<span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
                <!-- <input type="password" name="password1" value="{{ $writer->password }}" class="form-control" placeholder="Password"> -->
            </div>
        </div>

        <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
</div>
</form>
</div>
@endsection

resources/views/writers/index.blade.php
@extends('layouts.auth')

@section('content')
<head>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
<style>
	.btn.btn-add {
		margin-top: 10px;
		margin-bottom: 15px;
		margin-left: 20px;
	}

	.btn.btn-action {
		margin-top: 5px;
		margin-bottom: 5px;
		margin-left: 20px;
	}

	.header-text {
		margin-top: 20px;
		margin-left: 35px;
		font-size: 25px;
		font-family: 'Raleway', sans-serif;
		font-weight: bold;
	}

	.table {
		margin-left: 20px;
		margin-right: 0;
		width: 100%;
	}

    th {
		font-family: 'Raleway', sans-serif;
	}

    .alert {
        margin-left: 20px;
        max-height: 50px;
    }

</style>
</head>

<div class="row">
	<h3 class="header-text"> Manage Sellers </h3>
</div>

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-add btn-success" href="{{ route('writers.create') }}"> + Add New Seller</a>
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered table-hover">
	<thead>
    <tr>
        <th width="1%">#</th>
        <th width="20%">Name</th>
        <th width="20%">Email</th>
        <th width="30%">Action</th>
    </tr>
	</thead>
    @foreach ($writers as $writer)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $writer->name }}</td>
        <td>{{ $writer->email}}</td>
        <td>
            <form action="{{ route('writers.destroy',$writer->id) }}" method="POST">
  						<a class="btn btn-action btn-warning" href="{{ route('writers.edit',$writer->id) }}">Edit</a>


							<a class="btn btn-action btn-primary" href="{{ route('writers.editpassword',$writer->id) }}">Change Password</a>



                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-action btn-danger">Delete</button>


            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $writers->links() !!}

@endsection