routes/web.php
<?php
Route::get('/', 'ProductsController@home');
Auth::routes();

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('login.admin');
Route::get('/login/writer', 'Auth\LoginController@showWriterLoginForm')->name('login.writer');
Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm')->name('register.admin');
Route::get('/register/writer', 'Auth\RegisterController@showWriterRegisterForm')->name('register.writer');

Route::post('/login/admin', 'Auth\LoginController@adminLogin');
Route::post('/login/writer', 'Auth\LoginController@writerLogin');
Route::post('/register/admin', 'Auth\RegisterController@createAdmin')->name('register.admin');
Route::post('/register/writer', 'Auth\RegisterController@createWriter')->name('register.writer');

Route::view('/home', 'home')->middleware('auth');

Route::group(['middleware' => 'auth:admin'], function () {
    Route::view('/admin', 'admin');
    Route::resource('products','ProductController');
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
    Route::get('/writers/{writer}/editpassword', 'WriterController@editpassword')->name('writers.editpassword');
    Route::put('/writers/{writer}/updatepassword', 'WriterController@updatepassword')->name('writers.updatepassword');
    Route::resource('writers', 'WriterController');



});

Route::group(['middleware' => 'auth:writer'], function () {
    Route::view('/writer', 'writer');
    Route::resource('products','ProductController');
    Route::resource('category','CategoryController');
    Route::resource('orders','OrderController');


});


Route::group(['middleware' => 'auth'], function () {
    Route::view('/home', 'home');
    Route::view('/checkout','checkout');
    Route::view('/payment','payment');
    Route::view('/success','success');


    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

    //Route::resource('/maincategory','MainCategoryController');
    Route::resource('categorys','CategorysController');

    Route::get('cart', 'ProductsController@cart');




    Route::get('add-to-cart/{id}', 'ProductsController@addToCart');

    Route::patch('update-cart', 'ProductsController@update');

    Route::delete('remove-from-cart', 'ProductsController@remove');

    Route::get('/order', 'ProductsController@order')->name('orders');
    Route::post('/checkout/order', 'ProductsController@placeOrder')->name('place.order');
    Route::get('/orderdetails', 'ProductsController@vieworder')->name('view.order');

  //  Route::get('/showorder/{id}', 'ProductsController@showorder')->name('show.order');

    Route::get('/product', 'ProductsController@index');
    Route::patch('payment', 'ProductsController@updateorder')->name('payment');

    Route::resource('product','ProductsController');
    //Route::resource('order','OrderController');
    Route::get('/showorder/{id}', 'OrderController@show')->name('show.order');




});




Route::view('/logout','logout');
Route::view('/checkout','checkout');



Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@updateProfile')->name('profile.update');

app/Product.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{


      protected $fillable = [
          'name', 'price', 'unit', 'description', 'image','category_id',

      ];

      public function orders(){
            return $this->belongsToMany(Order::class);
        }
      /**
     * Get the category that the product belongs to.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);

    }
    public function writer()
    {
        return $this->belongsTo(Writer::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Auth;
use App\Product;
use App\Category;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = Product::latest()->paginate(5);

        return view('products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:100',
            'price' => 'required',
            'description' => 'required|max:200',
            'category_id' => 'required|numeric',
            'image' => 'mimes:jpeg,jpg,png|required|image|max:600',
            // 'supplier_id' => 'required|numeric',
            'unit' => 'required|numeric',
        ]);

              $image = $request->file('image');
              $imagedata = file_get_contents($image);
              $base64 = base64_encode($imagedata);

              $product = new Product();
              $product->name = $request->name;
              $product->description = $request->description;
              $product->price = $request->price;
              $product->category_id = $request->category_id;
              $product->image = $base64;
              // $product->supplier_id = $request->supplier_id;
              $product->writer_id = Auth::id();
              $product->unit = $request->unit;

              $product->save();
        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
      // Check if user is the post author
        if ($product->writer_id === Auth::id()) {
            return view('products.show',compact('product'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
      if ($product->writer_id === Auth::id()) {
        $categories = Category::all();
      return view('products.edit', compact('product', 'categories'));
      }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
          'name' => 'required|max:100',
          'price' => 'required',
          'description' => 'required|max:200',
          'category_id' => 'required|numeric',
          'image' => 'mimes:jpeg,jpg,png|image|max:600',
          // 'supplier_id' => 'required|numeric',
          'unit' => 'required|numeric',
        ]);

        if ($request->file('image') != null) {

            $image = $request->file('image');
            $imagedata = file_get_contents($image);
            $base64 = base64_encode($imagedata);

            $product->name = $request->name;
            $product->description = $request->description;
            $product->category_id = $request->category_id;
            $product->price = $request->price;
            $product->image = $base64;
            // $product->supplier_id = $request->supplier_id;
            $product->unit = $request->unit;
            $product->update();
        } else {
            $product->update($request->all());
        }

        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\Order;
use App\OrderItem;
class ProductsController extends Controller
{
  public function index()
      {
        $products = Product::all();
        $categories = Category::all();

       return view('products',compact('products','categories'))
           ->with('i', (request()->input('page', 1) - 1) * 5);
      }
      public function home()
          {
            $products = Product::all();
            $categories = Category::all();

          return view('main', compact('products','categories'));
          }

      public function cart()
      {
          return view('cart');
      }
      public function addToCart($id)
      {
        $product = Product::find($id);

                if(!$product) {

                    abort(404);

                }

                $cart = session()->get('cart');

                // if cart is empty then this the first product
                if(!$cart) {

                    $cart = [
                            $id => [
                                "name" => $product->name,
                                "quantity" => 1,
                                "price" => $product->price,
                                "image" => $product->image
                            ]

                    ];

                    session()->put('cart', $cart);
                  //  DB::table('products')->decrement('unit', $cart[$id]['quantity']);
                  DB::table('products')->where('id',$product->id)->decrement('unit', 1);

                    return redirect()->back()->with('success', 'Product added to cart successfully!');
                }


                // if cart not empty then check if this product exist then increment quantity
                if(isset($cart[$id])) {

                    $cart[$id]['quantity']++;

                    session()->put('cart', $cart);
                    DB::table('products')->where('id',$product->id)->decrement('unit', 1);



                    return redirect()->back()->with('success', 'Product added to cart successfully!');

                }

                // if item not exist in cart then add to cart with quantity = 1
                $cart[$id] = [
                    "name" => $product->name,
                    "quantity" => 1,
                    "price" => $product->price,
                    "image" => $product->image
                ];

                session()->put('cart', $cart);
                DB::table('products')->where('id',$product->id)->decrement('unit', 1);

                return redirect()->back()->with('success', 'Product added to cart successfully!');
      }

      public function update(Request $request, Product $product)
    {
        if($request->id and $request->quantity)
        {
            $cart = session()->get('cart');

            if($cart[$request->id]["quantity"]>$request->quantity){

              DB::table('products')->where('id',$request->id)->increment('unit', $cart[$request->id]["quantity"]-$request->quantity);

            }else {
              DB::table('products')->where('id',$request->id)->decrement('unit', $cart[$request->id]["quantity"]-$request->quantity);
            }
            $cart[$request->id]["quantity"] = $request->quantity;



            session()->put('cart', $cart);






            session()->flash('success', 'Cart updated successfully');

        }
    }

    public function remove(Request $request)
    {
        if($request->id) {

            $cart = session()->get('cart');

            if(isset($cart[$request->id])) {

              DB::table('products')->where('id',$request->id)->increment('unit',$cart[$request->id]["quantity"]);


                unset($cart[$request->id]);
                session()->put('cart', $cart);



            }

            session()->flash('success', 'Product removed successfully');
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('details',compact('product'));
    }



        /**
         * Remove the specified resource from storage.
         *
         * @param  \App\Product  $product
         * @return \Illuminate\Http\Response
         */
        public function destroy(Product $product)
        {
            $product->delete();

            return redirect()->route('products.index')
                            ->with('success','Product deleted successfully');
        }

        public function order(Request $request)
        {
          if(! $request->session()->has('cart')) {
        return "stop no session";
            }

            return view('order')
              ->with('orders', $request->session()->get('cart'));
        }

        public function placeOrder(Request $request)
        {
          $count=0;
          $total = 0;
          $carts = session()->get('cart');
          foreach ($carts as $id => $details) {
              $count++;
              $total += $details['price'] * $details['quantity'];
          }



          $order = Order::create([
        'order_number'      =>  'ORD-'.strtoupper(uniqid()),
        'user_id'           => auth()->user()->id,
        'status'            =>  'pending',
        'grand_total'       =>  $total,
        'item_count'        =>  $count,
        'payment_status'    =>  0,
        'payment_method'    =>  null,
        'first_name'        =>  $request->first_name,
        'last_name'         =>  $request->last_name,
        'address'           =>  $request->address,
        'phone_number'      =>  $request->phone_number,
        'transaction_date' => now(),
    ]);

    if ($order) {

          $items = session()->get('cart');

        foreach ($items as $id => $details)
        {
            // A better way will be to bring the product id with the cart items
            // you can explore the package documentation to send product id with the cart
            $product = DB::table('products')->where('id',$request->id)->first();

            $orderItem = new OrderItem([
                'product_id'    =>  $id,
                'quantity'      =>  $details['quantity'],
                'price'         =>  $details['price'],
            ]);

            $order->items()->save($orderItem);
        }
    }


    //return $order;
      $carts = session()->forget('cart');

      return view('checkout', compact('order'));
        }
        public function vieworder(Request $request)
        {
            $orders = Order::all();
            return view('orderdetails', compact('orders'));

        }
        public function updateorder(Request $request,Order $order)
        {
          // DB::table('orders')->where('id',$request->id)->update(['payment_status' => 'true']);

          $order->payment_status =$request->payment_status  ;
          $order->update();
          return redirect()->view('payment');
      }


}

resources/views/products/create.blade.php
<?php
use App\Common;
?>
@extends('layouts.auth')





@section('content')
<head>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(200)
                    .height(200);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<style>
	.btn.btn-back {
		margin-top: 20px;
		margin-bottom: 15px;
		margin-left: 20px;
	}

	.header-text {
		margin-top: 10px;
		margin-left: 20px;
		margin-bottom: 5px;
		font-size: 30px;
		font-family: 'Raleway', sans-serif;
		font-weight: bold;
	}

	.row.input-pic {
		margin-left: 8px;
		margin-bottom: 30px
	}

	.btn-add {
		margin-left: 13px;
		margin-bottom: 40px;
	}

	hr {
        margin-bottom: 20px;
    }

</style>
</head>

<div class="container">
	<div class="row">
		<a class="btn btn-back btn-primary" href="{{ route('products.index') }}"> Back</a>
	</div>

	<div class="row">
		<h3 class="header-text"> Add New Product </h3>
	</div>

	<hr>

	@if ($errors->any())
	<div class="alert alert-danger">
			<strong>Whoops!</strong> There were some problems with your input.<br><br>
			<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
			</ul>
	</div>
	@endif

	<form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
	@csrf

		<div class="row input-pic">
			<input type='file' onchange="readURL(this);" name="image" accept="image/png, image/jpeg" required focus/>
			<img id="blah" src="#" alt="your image" width="200" height="200"/>
			<span class="text-danger">{{ $errors->first('image') }}</span>
		</div>

		<hr>

		<div class="row">
			<div class="form-group col-md-6">
				<strong>Name:</strong>
				<input type="text" name="name" class="form-control" placeholder="Name" required focus>
				<span class="text-danger">{{ $errors->first('name') }}</span>
			</div>

			<div class="form-group col-md-12">
				<strong>Price:</strong>
        <input type="number" name="price" class="form-control" placeholder="Price" required focus>

			</div>

			<!-- <div class="form-group col-md-12">
				<strong>Supplier:</strong>
				<input type="number" name="supplier_id" class="form-control" placeholder="Supplier">
			</div> -->

			<div class="form-group col-md-12">
				<strong>Description:</strong>
				<textarea class="form-control" style="height:150px" name="description" placeholder="Description" required focus></textarea>
				<span class="text-danger">{{ $errors->first('description') }}</span>
			</div>

      <div class="form-group col-md-12">
				<strong>Category:</strong>
				<select class="form-control" name="category_id" required focus>
                    <option value="" disabled selected>Please select Category</option>
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{ $category->name }} - {{ $category->id }}</option>
                    @endforeach
                </select>
				<span class="text-danger">{{ $errors->first('category_id') }}</span>
			</div>

			<div class="form-group col-md-12">
				<strong>Unit:</strong>
				<input type="number" name="unit" class="form-control" placeholder="Unit" required focus>
				<span class="text-danger">{{ $errors->first('unit') }}</span>
			</div>

			<button type="submit" class="btn btn-add btn-success col-sm-2">Add</button>
		</div>
	</form>
</div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.auth')


@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .row.input-pic {
            margin-left: 8px;
            margin-bottom: 30px
        }

        .btn-update {
            margin-left: 13px;
            margin-bottom: 40px;
        }

        hr {
            margin-bottom: 20px;
        }
    </style>
</head>

<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('products.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Edit Product </h3>
    </div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row input-pic">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <!-- <label for="img">Select image:</label>
                    <input type="file" id="img" name="image" accept="image/*"> -->
                    <input type='file' onchange="readURL(this);" name="image" accept="image/png, image/jpeg" />
                    <img id="blah" src="data:image/jpeg;base64,{{$product->image}}" width="200" height="200" />
                    <span class="text-danger">{{ $errors->first('image') }}</span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Price:</strong>
                <input type="number" name="price" value="{{ $product->price }}" class="form-control" placeholder="Price">

                <span class="text-danger">{{ $errors->first('price') }}</span>
            </div>

            <!-- <div class="form-group col-md-12">
                <strong>Supplier ID:</strong>
                <input type="number" name="supplier_id" value="{{ $product->supplier_id }}" class="form-control" placeholder="Supplier ID">
            </div> -->

            <div class="form-group col-md-12">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $product->description }}</textarea>
                <span class="text-danger">{{ $errors->first('description') }}</span>
            </div>

            <div class="form-group col-md-12">
              <strong>Category:</strong>
              <select class="form-control" name="category_id" required focus>
                          <option value="" disabled selected>Please select Category</option>
                          @foreach($categories as $category)
                              <option value="{{$category->id}}">{{ $category->name }} - {{ $category->id }}</option>
                          @endforeach
                      </select>
              <span class="text-danger">{{ $errors->first('category_id') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Unit:</strong>
                <input type="number" name="unit" value="{{ $product->unit }}" class="form-control" placeholder="Unit">
                <span class="text-danger">{{ $errors->first('unit') }}</span>
            </div>

            <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
        </div>
    </form>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.auth')

@section('content')
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Utar E-Flea Market Inventory Management System</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('products.create') }}"> + Create New Product</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Image</th>
            <th>Price</th>
            <th>Unit</th>
            <th>Category</th>
            <th width="280px">Action</th>
        </tr>

        @foreach ($products->sortByDesc('updated_at') as $product)
        @if ($product-> writer_id == Auth::id())
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $product->name }}</td>
            <td width="1%"><img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" /></td>
            <td>{{ $product->price }}</td>
            <td>{{ $product->unit }}</td>
            <td width="8%"><a href={{ route('category.show',$product->category->id) }}>{{ $product->category -> name }}</a></td>
            <td>
                <form action="{{ route('products.destroy',$product->id) }}" method="POST">

                    <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>

                    <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
          @endif
        @endforeach

    </table>

    {!! $products->links() !!}

@endsection

resources/views/products/show.blade.php
@extends('layouts.auth')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row pic">
    <img id="blah" src="data:image/jpeg;base64,{{$product->image}}" width="300" height="300" />
</div>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $product->description }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                {{ $product->price }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Unit:</strong>
                {{ $product->unit }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Category:</strong>
                {{ $product->category -> name }}
            </div>
        </div>
    </div>
@endsection